### ISSUE TITLE
Quest not enough require item

### ISSUE THREAD

**Issue by Kiriao** [DragoNext/AqwDoIhave#11]
![image](https://user-images.githubusercontent.com/48480973/204746117-7b3853ff-4691-4120-baa9-529ff4f2e5f9.png)
Shouldn't the color change if the item doesn't match with it require item number?

**Comment by DragoNext** [comment]
Fixed it:
![image](https://user-images.githubusercontent.com/49029552/204811846-9ac5522a-bb01-4bcc-afe2-4862b702c6d7.png)
