### ISSUE TITLE
Unidentified_Translation not working

### ISSUE THREAD

**Issue by Kiriao** [DragoNext/AqwDoIhave#3]
After i get the new zip the Unidentified Translation seem like stop working. 

![image](https://user-images.githubusercontent.com/48480973/201040300-704ea7aa-7016-4a3d-a9e0-bf67ea199066.png)

**Comment by DragoNext** [comment]
My bad the translation code was not lowering the case of element text will fix that shortly, sorry.

**Comment by DragoNext** [comment]
05e47d5 fixed it was caused by typo when changing to lowercase matching.
