### ISSUE TITLE
[Bug] Item is number

### ISSUE THREAD

**Issue by Kiriao** [DragoNext/AqwDoIhave#5]
Hi, i found 1 more issue, the recent event there item Duck Norris Meme 1 to 20 and it not detecting it in my inventory

**Comment by DragoNext** [comment]
Unfortunately can't do nothing about it as "https://account.aq.com/AQW/Inventory" just doesn't detect these items 
![image](https://user-images.githubusercontent.com/49029552/202973078-25dc66f4-7381-41ec-a445-b4333c199968.png)
, it is not even visible on https://account.aq.com/CharPage 
![image](https://user-images.githubusercontent.com/49029552/202973274-ba01f43e-5cfa-4b11-9722-e520a4a8e7f7.png)

, not my fault for no detection as it is not present in AQ system for that item...
(I also have it in my inventory)
![image](https://user-images.githubusercontent.com/49029552/202973315-d2b5479e-d3c3-4d69-9c41-032ad6413c0c.png)

Sorry can't repair what's not broken by me, needs to be reported AQW developers as bug (Will do that)

**Comment by Kiriao** [comment]
Ahh i see. Thanks for your awesome extension!
