### ISSUE TITLE
Comment on the new feature "Count total resources" from merge shop.

### ISSUE THREAD

**Issue by Quannh1511** [DragoNext/AqwDoIhave#6]
Hi DragoNext,

It's me again, after a while of experiencing the extension, I find it works relatively smoothly. But I'm a lazy person, I spend a lot of time going to merge shop sites to find unfarmed items, where I have to calculate resources together so it's very time consuming, even wrong and omission. I can also make a separate extension to calculate, but no, I think your extension should update this function, it saves people from having to calculate when they want to farm something in the merge shop.

Here is my idea for the merge shop resource totaling section.
1. Only really counted when in the website has the keyword "Merge Shops", and displays the UI filter.
2. Only take items that do not exist in the inventory to calculate the total resource.
3. As for the filter, I'd like to have the option to count items with the Ac tag and All. (I'm a collector so I'm only interested in Ac tag items)

Those are the ideas that I want to present to you, hope you can handle this part.

Thank you, good luck.

![Screenshot 2022-11-26 210459](https://user-images.githubusercontent.com/107485615/204093587-79b55853-9db5-4717-a3f4-1b3bc96bc04b.png)

**Comment by Quannh1511** [comment]
You should also pay attention to this part.

![image](https://user-images.githubusercontent.com/107485615/204093795-48348b9c-53ad-4566-8ce2-4fba1ff555bd.png)

**Comment by Quannh1511** [comment]
Do you have a solution to display the price of that item as shown below?
![image](https://user-images.githubusercontent.com/107485615/204094500-53b58726-396d-4cb1-9dfb-2e663af35a35.png)

I want items that don't exist in the inventory to also display prices so I don't have to go to their detail link.
![image](https://user-images.githubusercontent.com/107485615/204094537-e6454827-9c08-4a4c-8d9c-e0c4ed553a1b.png)

**Comment by Quannh1511** [comment]
I have the item but it doesn't recognize, is this a feature or a bug?
![image](https://user-images.githubusercontent.com/107485615/204095313-6e440313-ca24-434a-8f30-8e88681ecf10.png)

**Comment by DragoNext** [comment]
With not detecting "Hollowborn Residue" Did you update inventory after getting it? i tested it and it does detect without problem.
And with you problem "I spend a lot of time going to merge shop sites to find unfarmed items" i will have fix for you soon :) 
![image](https://user-images.githubusercontent.com/49029552/204097257-cdb78bd9-d11e-4a30-9f17-6e2adc23a396.png)
(That's what i'm currently working on, using that data will be much easier to make the new features:
Find unfarmed Items.
Calculate Total Cost (With link to quests and mobs that drop items)
And 3. is a relatively new idea to filter ac tags will work on that shouldn't be too hard to implement.


Currently finishing scraper for aqwwiki items should be done in few days, and will start implementing other features.

**Comment by Quannh1511** [comment]
Here the item is armor, not resource, I'm not clear.
![image](https://user-images.githubusercontent.com/107485615/204097486-c59c1459-ef0e-4488-954c-da132eca8eef.png)

**Comment by DragoNext** [comment]
Oh that's what you mean, currently the title on top of wiki is not included in detection of items, should be able to add it easily will do that in few hours, as i'm done on filtering items out.

**Comment by Quannh1511** [comment]
One side issue, are you able to access the data in aqw game to get all the data?. It's a good resource to support the aqw wiki.

**Comment by DragoNext** [comment]
Not without modifying the clients .swf file, tried to find ways to get data from inventory and bank but without some packet logger on client side it isn't really possible.
Good example of packet logging is this project https://github.com/r-0-x/AQW-Master
And if you mean ALL data of all items not really as AQW is instance based and sends data per request it doesn't store data locally of all items, it loads them locally on fly, same for locations, monsters etc.

**Comment by Quannh1511** [comment]
According to the image you provided, I'm guessing that this is a file containing all the item data on the aqw wiki? And how do you get them? can you tell me?

**Comment by Quannh1511** [comment]
> 

I understand, but they probably won't provide api to developers

**Comment by DragoNext** [comment]
AqwWiki scraping using python, basically going through Items Categories going through for example:
"http://aqwwiki.wikidot.com/armors" and then getting all items and max page number then requesting next page by > "http://aqwwiki.wikidot.com/armors/p/{PageNumber}" and just creating list of link for these items eg.  "/abyssal-angel-ac" and then going through that list and getting all details, and then parsing them to make whole json data.

And yes they will not provide but when they will make AQ2D/AqwMobile it will be much easier to mod for it as it will be on unity (BepInEx) :)

**Comment by Quannh1511** [comment]
According to the current situation, we can only help the player find related items with 90% accuracy (I think). I have also joined the wiki editor to correct the information, which will increase the accuracy of the comparison.

**Comment by Quannh1511** [comment]
Oh, I think you have a secret source from the wiki, but you're a data crawler like me. I also use Nodejs for scraping.

**Comment by Quannh1511** [comment]
This is an excel file containing the items that have been compared with the aqw wiki, and it will show what items are available and not. Accuracy is also not absolute.

![image](https://user-images.githubusercontent.com/107485615/204098713-6b054766-d22f-4b06-9022-933d6a4920a8.png)

**Comment by Quannh1511** [comment]
But my software is probably not as detailed as yours.

**Comment by DragoNext** [comment]
Mine gets much more detail as price: (Shop) (Merge Shop) (Drop) (Quest) etc.
Which also handles multiple monsters, and merge items.
And basically how i handle accuracy is just to avoid edge cases there were quite a few when i developed it:
Some aqwiki pages instead of "GOLD" have "Gold" same for "AC"
Also:
"N/A (Reward from the " + Quest names sometimes is " N/A (Reward from " etc. etc.
But still with my internet connection 2mbs going through 1.3gb of pages data takes a while so debugging it takes quite a bit time, (Excluding individual items i can check item if i know which is wrong)

**Comment by DragoNext** [comment]
Oh yeah i was making weapon spread sheet https://docs.google.com/spreadsheets/d/1m4IPHJjS3M3rvHNJfQLKZcHougjDkxG8NaVWNmzKihY/edit#gid=0 but still working on damage boost detection for scraper :|

**Comment by Quannh1511** [comment]
> Mine gets much more detail as price: (Shop) (Merge Shop) (Drop) (Quest) etc. Which also handles multiple monsters, and merge items. And basically how i handle accuracy is just to avoid edge cases there were quite a few when i developed it: Some aqwiki pages instead of "GOLD" have "Gold" same for "AC" Also: "N/A (Reward from the " + Quest names sometimes is " N/A (Reward from " etc. etc. But still with my internet connection 2mbs going through 1.3gb of pages data takes a while so debugging it takes quite a bit time, (Excluding individual items i can check item if i know which is wrong)

Haha, I understand. In the beginning it also took me a lot of time to debug, each time refreshing my data took about 6 - 7 minutes. But my goal is not the same as yours, I only show brief information for users to recognize. But later, like me now, there are many items, so using your extension is very good.

**Comment by Quannh1511** [comment]
> > Mine gets much more detail as price: (Shop) (Merge Shop) (Drop) (Quest) etc. Which also handles multiple monsters, and merge items. And basically how i handle accuracy is just to avoid edge cases there were quite a few when i developed it: Some aqwiki pages instead of "GOLD" have "Gold" same for "AC" Also: "N/A (Reward from the " + Quest names sometimes is " N/A (Reward from " etc. etc. But still with my internet connection 2mbs going through 1.3gb of pages data takes a while so debugging it takes quite a bit time, (Excluding individual items i can check item if i know which is wrong)
> 
> Haha, I understand. In the beginning it also took me a lot of time to debug, each time refreshing my data took about 6 - 7 minutes. But my goal is not the same as yours, I only show brief information for users to recognize. But later, like me now, there are many items, so using your extension is very good.

I think, what we want the most right now is aqw manager to provide more price columns.

**Comment by Quannh1511** [comment]
> > > Mine gets much more detail as price: (Shop) (Merge Shop) (Drop) (Quest) etc. Which also handles multiple monsters, and merge items. And basically how i handle accuracy is just to avoid edge cases there were quite a few when i developed it: Some aqwiki pages instead of "GOLD" have "Gold" same for "AC" Also: "N/A (Reward from the " + Quest names sometimes is " N/A (Reward from " etc. etc. But still with my internet connection 2mbs going through 1.3gb of pages data takes a while so debugging it takes quite a bit time, (Excluding individual items i can check item if i know which is wrong)
> > 
> > 
> > Haha, I understand. In the beginning it also took me a lot of time to debug, each time refreshing my data took about 6 - 7 minutes. But my goal is not the same as yours, I only show brief information for users to recognize. But later, like me now, there are many items, so using your extension is very good.
> 
> I think, what we want the most right now is aqw manager to provide more price columns.

They provide it at buyback but not for inventory :)

**Comment by DragoNext** [comment]
My motivation for making it was basically: Did i get that drop from monster? xD

**Comment by Quannh1511** [comment]
> Oh yeah i was making weapon spread sheet https://docs.google.com/spreadsheets/d/1m4IPHJjS3M3rvHNJfQLKZcHougjDkxG8NaVWNmzKihY/edit#gid=0 but still working on damage boost detection for scraper :|

Why are you research this section? I haven't found it useful yet.

**Comment by Quannh1511** [comment]
> My motivation for making it was basically: Did i get that drop from monster? xD

I'm a collector, I want a lot of Ac tag items :)

**Comment by DragoNext** [comment]
I was thinking of all Unstable Weapons, Stable etc. mainly but on further thinking NSoD is the best :( 
Sword Variation sucks in Aqw

**Comment by DragoNext** [comment]
Still remember times where unstable weapons where more sought after.

**Comment by Quannh1511** [comment]
oh, but usually I see them doing boost items. They do it manually. :)

> I was thinking of all Unstable Weapons, Stable etc. mainly but on further thinking NSoD is the best :( Sword Damage Variation sucks in Aqw

oh, but usually I see them doing boost items. They do it manually. :)

**Comment by Quannh1511** [comment]
> I was thinking of all Unstable Weapons, Stable etc. mainly but on further thinking NSoD is the best :( Sword Damage Variation sucks in Aqw

oh, but usually I see them doing boost items. They do it manually. :)

**Comment by DragoNext** [comment]
Summary:
Added hiding non Ac items in merge shops.
Repaired Typo.
Informed about future development info, working on scraper when done will add few new features (See new issues)

**Comment by Quannh1511** [comment]
Perhaps you misunderstood filter. I just want it to work as a calculation. When selecting the Ac option, it will calculate the resources that have the Ac tag, and when selecting All, it will sum all the items that appear. And when calculating, it will not count the items that are already in the inventory.
